#!/usr/bin/env python
"""
Demo API fill for the onboarding application flow.

Drives the public API exactly like a real client would:
    1. POST /api/applications/                       -> create applicant (details only)
    2. POST /api/applications/<id>/quiz/start/        -> build the shuffled session
    3. GET  /api/quiz/<session>/current/             -> fetch the current question
    4. POST /api/quiz/<session>/answer/              -> submit an answer  (repeat)
    5. GET  /api/quiz/<session>/result/              -> final score
    6. POST /api/applications/<id>/finalize/          -> motivation + expectations + CV
                                                        (only if the score passed)

Usage:
    # 1. start the server in one terminal:
    #    .venv/Scripts/python.exe manage.py runserver
    # 2. run this demo in another:
    python demo_fill.py
    python demo_fill.py --base-url http://127.0.0.1:8000 --answers correct

--answers correct  (default) looks up the right answer via the Django ORM so the
                   run ends with a perfect score (nice for demos).
--answers first    picks the first option every time -- pure API, no DB access.
"""

import argparse
import io
import json
import mimetypes
import os
import sys
import urllib.error
import urllib.request
import uuid

# A realistic-looking applicant payload (mirrors the Application model fields).
APPLICANT = {
    "first_name": "Ada",
    "last_name": "Lovelace",
    "email": "ada.lovelace@example.org",
    "phone": "+44 20 7946 0958",
    "nationality": "British",
    "country_of_residence": "United Kingdom",
    "gender": "Female",
    "institution": "Analytical Engine Institute",
    "institution_type": "University",
    "role": "Research Scientist",
    "education": "PhD",
    "r_experience": "Intermediate",
    "bayesian_knowledge": "Beginner",
}

# Collected in the final step, after the quiz has been passed.
FINAL_STEP = {
    "motivation": "I want to apply spatial Bayesian methods to malaria risk mapping.",
    "expectations": "Hands-on experience with sf, ggplot2 and Bayesian workflows in R.",
}

CV_BYTES = (
    b"Ada Lovelace -- Curriculum Vitae\n"
    b"Research Scientist, Analytical Engine Institute\n\n"
    b"Skills: R, spatial data (sf), Bayesian statistics.\n"
    b"(Demo CV generated by demo_fill.py)\n"
)


def _encode_multipart(fields, file_field, filename, file_bytes):
    """Build a multipart/form-data body from plain fields + one file."""
    boundary = f"----demo{uuid.uuid4().hex}"
    crlf = b"\r\n"
    buf = io.BytesIO()

    for name, value in fields.items():
        buf.write(f"--{boundary}".encode() + crlf)
        buf.write(f'Content-Disposition: form-data; name="{name}"'.encode() + crlf)
        buf.write(crlf)
        buf.write(str(value).encode("utf-8") + crlf)

    content_type = mimetypes.guess_type(filename)[0] or "application/octet-stream"
    buf.write(f"--{boundary}".encode() + crlf)
    buf.write(
        f'Content-Disposition: form-data; name="{file_field}"; filename="{filename}"'.encode()
        + crlf
    )
    buf.write(f"Content-Type: {content_type}".encode() + crlf)
    buf.write(crlf)
    buf.write(file_bytes + crlf)

    buf.write(f"--{boundary}--".encode() + crlf)
    return buf.getvalue(), f"multipart/form-data; boundary={boundary}"


def _request(method, url, *, data=None, headers=None):
    req = urllib.request.Request(url, data=data, method=method, headers=headers or {})
    try:
        with urllib.request.urlopen(req) as resp:
            body = resp.read().decode("utf-8")
            return resp.status, json.loads(body) if body else None
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8")
        try:
            return exc.code, json.loads(body)
        except json.JSONDecodeError:
            return exc.code, body


def _load_answer_key():
    """Map question text -> correct answer via the Django ORM (for a perfect run)."""
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "onboarding.settings")
    import django

    django.setup()
    from application.models import Question

    return {q.text: q.correct_answer for q in Question.objects.all()}


def main():
    parser = argparse.ArgumentParser(description="Demo API fill for the onboarding app.")
    parser.add_argument("--base-url", default="http://127.0.0.1:8000")
    parser.add_argument("--answers", choices=["correct", "first"], default="correct")
    args = parser.parse_args()

    base = args.base_url.rstrip("/")
    answer_key = _load_answer_key() if args.answers == "correct" else {}

    print(f"-> Creating application at {base}/api/applications/ ...")
    status, app = _request(
        "POST",
        f"{base}/api/applications/",
        data=json.dumps(APPLICANT).encode(),
        headers={"Content-Type": "application/json"},
    )
    if status != 201:
        print(f"[x] Failed to create application ({status}): {app}")
        sys.exit(1)
    application_id = app["id"]
    print(f"  [ok] Application created: {application_id} ({app['first_name']} {app['last_name']})")

    print("-> Starting quiz ...")
    status, current = _request(
        "POST", f"{base}/api/applications/{application_id}/quiz/start/"
    )
    if status != 201:
        print(f"[x] Failed to start quiz ({status}): {current}")
        sys.exit(1)
    session_id = current["session"]
    total = current["total"]
    print(f"  [ok] Session {session_id} - {total} questions\n")

    answered = 0
    while current and current.get("question"):
        q = current["question"]
        position = current["position"]
        options = q["options"]

        if args.answers == "correct":
            answer = answer_key.get(q["text"], options[0])
        else:
            answer = options[0]

        print(f"  Q{position + 1}/{total} [{q['category']}] {q['text']}")
        print(f"     -> answering: {answer!r}")

        status, resp = _request(
            "POST",
            f"{base}/api/quiz/{session_id}/answer/",
            data=json.dumps({"answer": answer}).encode(),
            headers={"Content-Type": "application/json"},
        )
        if status != 200:
            print(f"[x] Answer rejected ({status}): {resp}")
            sys.exit(1)
        answered += 1

        if resp.get("finished"):
            break
        current = resp.get("next")

    print(f"\n-> Fetching result ({answered} answered) ...")
    status, result = _request("GET", f"{base}/api/quiz/{session_id}/result/")
    print(f"  [ok] Score: {result['score']} / {result['total']}  (completed_at={result['completed_at']})")

    if not result.get("passed"):
        print(
            f"  [--] Score below the pass mark ({result.get('pass_mark')}) -- "
            f"the final step stays locked."
        )
        return

    print("\n-> Submitting the final step (motivation, expectations, CV) ...")
    body, content_type = _encode_multipart(
        FINAL_STEP, "cv", "ada_lovelace_cv.txt", CV_BYTES
    )
    status, final = _request(
        "POST",
        f"{base}/api/applications/{application_id}/finalize/",
        data=body,
        headers={"Content-Type": content_type},
    )
    if status != 200:
        print(f"[x] Final submission rejected ({status}): {final}")
        sys.exit(1)
    print(f"  [ok] Application submitted at {final['submitted_at']} (cv={final['cv']})")


if __name__ == "__main__":
    main()
