# Generated by Django 6.0.7 on 2026-07-28 11:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('nationality', models.CharField(max_length=100)),
                ('country_of_residence', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('institution', models.CharField(max_length=200)),
                ('institution_type', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=150)),
                ('education', models.CharField(max_length=30)),
                ('r_experience', models.CharField(max_length=30)),
                ('bayesian_knowledge', models.CharField(max_length=30)),
                ('motivation', models.TextField(blank=True)),
                ('expectations', models.TextField(blank=True)),
                ('cv', models.FileField(upload_to='cvs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('R', 'R programming'), ('SPATIAL', 'Spatial data'), ('BAYESIAN', 'Bayesian statistics'), ('APPLICATION', 'Health applications')], max_length=20)),
                ('options', models.JSONField(help_text='List of option strings shown to the applicant.')),
                ('correct_answer', models.CharField(max_length=255)),
                ('time_limit_seconds', models.PositiveIntegerField(default=40)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='application.application')),
            ],
        ),
        migrations.CreateModel(
            name='SessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_answer', models.CharField(blank=True, max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('timed_out', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='application.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='application.quizsession')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('session', 'position')},
            },
        ),
    ]
