# Generated by Django 6.0.7 on 2026-07-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_application_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='decision',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='application',
            name='decision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(default='', upload_to='cvs/'),
            preserve_default=False,
        ),
    ]
