# Generated by Django 6.0.7 on 2026-08-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_add_decision_and_require_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='final_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(blank=True, upload_to='cvs/'),
        ),
    ]
