# Generated by Django 6.0.7 on 2026-08-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_application_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sessionquestion',
            name='option_order',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('R', 'R programming'), ('SPATIAL', 'Spatial data'), ('GENERAL', 'General statistics'), ('BAYESIAN', 'Bayesian statistics'), ('APPLICATION', 'Health applications')], max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
