# Generated by Django 6.0.7 on 2026-08-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_question_code_sessionquestion_option_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='claims',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='application',
            name='elig_attend',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='application',
            name='elig_data',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='application',
            name='elig_funding',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='application',
            name='elig_laptop',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='application',
            name='exp_bayes',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='application',
            name='exp_dtype',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='application',
            name='exp_glm',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='application',
            name='exp_rfreq',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='application',
            name='exp_rself',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='application',
            name='exp_share',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='application',
            name='exp_use',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='application',
            name='exp_when',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='application',
            name='ineligible_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='written_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='written_dataset',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='written_other',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='written_why_not_ols',
            field=models.TextField(blank=True),
        ),
    ]
