# Generated by Django 6.0.2 on 2026-08-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_application_claims_application_elig_attend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(blank=True, upload_to='cvs/'),
        ),
    ]
